#spring:
#  datasource:
#    username: traning_test
#    password: Training_d8ayx6
#    url: jdbc:mysql://10.125.131.243:50294/hn_traning?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
#  redis:
#    cluster:
#      nodes: 10.125.10.235:32713,10.125.10.234:32727,10.125.11.124:32777,10.125.10.233:32777,10.125.11.126:32727,10.125.11.125:32725
#      maxIdle: 1000
#      minIdle: 200
#      maxTotal: 1000
#      maxWaitMills: 3000
#      connectionTimeout: 2000
#      testOnBorrow: true
#      testOnReturn: true
#      password: RdsTn2022$#
#    database: 0
#    timeout: 2000
#    password: RdsTn2022$#
#
#    jedis:
#      pool:
#        max-active: 50
#        max-idle: 30
#        maxWait: 50000
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.19.85.84:8848
#        #        register-enabled: true
#        namespace: c118c652-51fe-476d-aad3-147dc4f4945e
#
#
## 文件上传
#minio:
#  url: http://10.19.85.84:9000
#  accessKey: minioadmin
#  secretKey: minioadmin
#  bucketName: bpme
## 联通云文件上传
#cos:
#  bucket: hnkk-dev
#  accessKey: E15PZNPIHF32M496GAKU
#  secretKey: w3zIOCECWkjeuoc1AEPlnTIZtC6BSnA2gdHtKocU
#  serviceEndpoint: cos.xx-tst.cos.tg.unicom.local
#  region: xx-tst
#  fileBaseUrl: https://cos.xx-tst.cos.tg.unicom.local/142103562682:hnkk-dev/
## 文件上传服务选择
#fileUploadConfigParam: minio
#
#oss:
#  endpoint: http://10.125.119.169
#  accesskey: GFzGKhYPORNpzwl8
#  accessKeySecret: pNYaqniCxlIp0nYZ7UQS7V0d50w6HI
#  bucketName: bucket-testpms